### ISSUE TITLE
Feature Request:  Docker Image

### ISSUE THREAD

**Issue by ItsNoted** [TechSquidTV/Shoutify#42]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues.

### Describe the solution you'd like.

A Docker image would be great for simple installation.

### Teachability, documentation, adoption, migration strategy.

N/A

### What is the motivation / use case for changing the behavior?

Make it easier to install.

**Comment by takanome-dev** [comment]
Hey @ItsNoted, thanks for taking the time to put this together. We really appreciate your concern about this project.

Right now, though, I think we're going to close this because this project is still in its early stages.
If things change in the short or long term, we will consider reopening this issue.

Again, we appreciate your time and invite your input.

#### You may join our [Discord](https://discord.gg/CTC9DVvYZz) and talk about Shoutify
